name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Publish
          uses: dawidd6/action-docker-publish-changed@master
          with:
            docker_username: ${{secrets.DOCKER_LOGIN}}
            docker_password: ${{secrets.DOCKER_PASS}}
            github_token: ${{secrets.GITHUB_TOKEN}}
            platforms: linux/amd64,linux/arm64,linux/arm
