name: Publish images

on:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Publish
      uses: dawidd6/action-docker-publish-changed@master
      with:
        docker_username: ${{secrets.DOCKER_LOGIN}}
        docker_password: ${{secrets.DOCKER_PASS}}
        github_token: ${{secrets.GITHUB_TOKEN}}
        platforms: linux/amd64,linux/arm64,linux/arm
